<%
# Hack to fix a bug in TK. TK supports using an SSH gateway in its SSH transport, but appears not to support configuring
# separate keys for the gateway and the destination.
require 'kitchen/transport/ssh'

GATEWAY_KEYS = ["#{ENV['HOME']}/.ssh/identity.lyra"]

class Kitchen::Transport::Ssh::Connection
  # Replace this method in TK core with a version that uses the logged in user's key to access the SSH gateway.
  def establish_connection_via_gateway(opts)
    retry_connection(opts) do
      Net::SSH::Gateway.new(ssh_gateway, ssh_gateway_username, options.merge(keys: GATEWAY_KEYS))
        .ssh(hostname, username, options)
    end
  end
end
%>
---
driver:
  name: vagrant
  provider: libvirt
  vagrantfiles:
    - 'test/fixtures/Vagrantfile.libvirt-ssh'
  synced_folders:
  - [".", "/tmp/kitchen/soloist", "disabled: false, type: 'rsync'"]
#    ssh_gateway_username: trinitronx

#  customize:
#    memory: 1024

transport:
  ssh_gateway: saturn.local
  ssh_gateway_username: trinitronx
#  username: vagrant

provisioner:
#  name: chef_zero
  transport:
    ssh_gateway: saturn.local
    ssh_gateway_username: trinitronx

#  deprecations_as_errors: true
  deprecations_as_errors: false
#  multiple_converge: 2
#  enforce_idempotency: true

verifier:
  name: inspec
## Client error, can't connect to 'ssh' backend: Only one of proxy_command or bastion_host needs to be specified]
## Apparently the transport ssh_gateway option is actually passed through to InSpec
#  proxy_command: ssh saturn.local -q0 %h:%p

platforms:
  - name: ubuntu-20.04
    driver:
      box: generic/ubuntu2004
    lifecycle:
      pre_converge:
      - remote: sudo addgroup --system admin
      - remote: sudo usermod -a -G admin kitchen
  - name: macos-latest
    driver:
      box: lyraphase-runner/macos-monterey-base
      box_url: http://saturn.local:8888/lyraphase-runner-macos-monterey-base.box
      communicator: ssh
      gui: true
      customize:
        memory: 4096
#        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[sprout-base::default]
    attributes:
      mysql_test:
        version: '8.0'
#    includes: [ubuntu-20.04, macos-latest]
