---
name: ci

"on":
  pull_request:
    branches:
      - master
      - main
      - develop
  push:
    branches:
      - master
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run make test
        run: |
          bundle exec make test
  bootstrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Add --no-document to .gemrc
        run: |
          tee -a $HOME/.gemrc <<EOGEMRC
          install: --no-document
          update: --no-document
          EOGEMRC
      - name: Run bootstrap.sh + soloist with test fixtures
        run: |
          cd ./test/fixtures
          make -C ../../ bootstrap
