# Merge PRs labeled release to master

name: git-flow-automerge

# Controls when the workflow will run
on:
  # Trigger on pull request events tagged 'release' only for the develop branch
  pull_request:
    branches: [ develop ]
    types: [ labeled, closed, edited ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  master-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Extract master SHA
        run: echo "sha=$(git rev-parse master)" >> "$GITHUB_OUTPUT"
        id: master_branch
      - name: Check triggering user permissions
        id: check_user_permissions
        uses: actions-cool/check-user-permission@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.triggering_actor }}
          require: write
    outputs:
      sha: ${{ steps.master_branch.outputs.sha }}
      authorized: ${{ steps.check_user_permissions.outputs.require-result }}
  automerge:
    if: format('{0}', needs.master-branch.outputs.authorized) == 'true' && github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'release') || github.event.label.name == 'release')
    runs-on: ubuntu-latest
    needs: master-branch
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Extract Chef Version
        run: |
          bundle exec gem list --quiet --local --exact 'chef' | \
          ruby -ne 'version = gsub(/chef\s*\((?<version>.*)\)$/, %q/\k<version>/); \
                    print "chef_version=#{version.chomp}"' >> "$GITHUB_OUTPUT"
        id: extract_chef_version
      - name: Set release/chef-version branch name
        run: |
          echo 'branch=release/chef-v${{ steps.extract_chef_version.outputs.chef_version }}' >> "$GITHUB_OUTPUT"
        id: chef_release
      - uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.LYRAPHASE_RUNNER_AUTOMERGE_TOKEN }}
        with:
          branch: ${{ steps.chef_release.outputs.branch }}
          sha: ${{ needs.master-branch.outputs.sha }}
      - name: git-flow-merge-action
        uses: trinitronx/git-flow-merge-action@fix-559-update-nodejs-to-v20
        with:
          github_token: ${{ secrets.LYRAPHASE_RUNNER_AUTOMERGE_TOKEN }}
          branch: 'develop'
          # Can't turn off merging branch into both: develop_branch & main_branch... so hack it to just do master
          develop_branch: ${{ steps.chef_release.outputs.branch }}
          main_branch: 'master'
