---
name: yaml-syntax

"on":
  pull_request:
    branches:
      - master
      - main
      - develop
    paths:
      - 'soloistrc**'
  push:
    branches:
      - master
      - main
      - develop
    paths:
      - 'soloistrc**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run make test
        run: |
          bundle exec make test
